# Generated by Django 5.0.6 on 2024-07-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('budget', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('Cash', 'cash'), ('UPI', 'upi'), ('Card', 'card')], default='cash', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=200)),
                ('category_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
